### ISSUE TITLE
difficult to know what changed

### ISSUE THREAD

**Issue by willkg** [gengo/gengo-python#58]
gengo-python 0.1.26 is the latest release on pypi, but isn't tagged in this repository. Further, there don't appear to be any tags in this repository between 0.1.19 and 0.1.27.

gengo-python 0.1.27 is tagged in this repository (15 hours ago as of this writing), but isn't on pypi.

The `CHANGELOG.rst` is curious and possibly suggests it doesn't get updated very often.

The way this project is being maintained makes it difficult to understand to use. It's hard to know what changed between versions so that I can update my gengo-python-using code appropriately.

Can you backfill the tags and update the CHANGELOG with the releases that are missing? For versions that were skipped and never released, it helps to have a note in the CHANGELOG about that.

**Comment by chris-erickson** [comment]
[You and me both.](https://github.com/gengo/gengo-python/issues/27)

**Comment by willkg** [comment]
On projects I maintain, I usually have a release process that lists all the steps required to do a release. That way I don't have to think about it and I don't forget one.

I've seen other people script the release process and put the scripts in the repository alongside the code. For example, jinja2 has a release script: https://github.com/mitsuhiko/jinja2/blob/master/scripts/make-release.py

Seems like either one of those would help here.

**Comment by hayate** [comment]
@willkg and @chris-erickson thank you for your feedback.

For lack of resources our api libraries are not always maintain as we wish, will try to put some of your advise into practice.

The latest tagged release is not yet on pypi as it includes updates that we made to the api that will be released and documented in few days. Didn't think that would create too much confusion, will definitely only tag releases that are also immediately uploaded to pypi in the future.

**Comment by chris-erickson** [comment]
:clap: Thanks!

**Comment by narusemotoki** [comment]
We have CHANGELOG now. Thank you for your great advice.
https://github.com/gengo/gengo-python/blob/master/CHANGELOG.rst
